name: the_greatest_sensitivity_mapper
channels:
  - astropy
  - defaults
  - conda-forge
dependencies:
  - python
  - ipython
  - numpy
  - scipy
  - matplotlib
  - astropy
  - numba
  - ipywidgets
  - reproject
  - xmltodict
  - bottleneck
  - ipympl
