name: the_greatest_sensitivity_mapper
channels:
  - astropy
  - conda-forge
  #- defaults
dependencies:
  - python
  - ipython
  - numpy
 # - scipy
  - matplotlib
  - astropy
  - numba
  - ipywidgets
  - reproject
  - xmltodict
  - bottleneck
  - ipympl
